name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      uses: uraimo/run-on-arch-action@v1.0.7
      with:
        architecture: aarch64
        distribution: ubuntu18.04
        run: |
          apt-get update
          apt-get install -y docker.io
          docker build .
